apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-service-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: dev
        url: https://kubernetes.default.svc
      - env: stage
        url: https://kubernetes.default.svc
      - env: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.namespace}}'
    spec:
      project: hello-service
      source:
        repoURL: https://github.com/shamsmali/hello-service-a-deploy.git
        targetRevision: HEAD
        path: 'deploy/{{.env}}'
      destination:
        server: '{{.url}}'
        namespace: 'hello-service-{{.env}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true