apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-service-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - namespace: hello-service-a-dev
        url: https://kubernetes.default.svc
      - namespace: hello-service-a-stage
        url: https://kubernetes.default.svc
      - namespace: hello-service-a-prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.namespace}}'
    spec:
      project: hello-service
      source:
        repoURL: https://github.com/shamsmali/hello-service-a-deploy.git
        targetRevision: HEAD
        path: deploy
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true