apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-service-a-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/shamsmali/hello-service-a-deploy.git
    targetRevision: HEAD
    path: deploy
  destination: 
    server: https://kubernetes.default.svc
    namespace: hello-service-a

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true