apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-service-a-app
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - namespace: hello-service-a-dev
        url: https://kubernetes.default.svc
      - namespace: hello-service-a-stage
        url: https://kubernetes.default.svc
      - namespace: hello-service-a-prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-hello-service-a'
    spec:
      project: hello-service-a
      source:
        repoURL: https://github.com/infra-team/cluster-deployments.git
        targetRevision: HEAD
        path: guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: '{{.cluster}}-hello-service-a
