apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: HelloService
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destinations:
  # Do not allow any app to be installed in `kube-system`  
  - namespace: '!kube-system'
    server: '*'
  - namespace: '*'
    server: '*'